version: 2.1

orbs:
  snyk: pagerduty/snyk@2  # https://circleci.com/developer/orbs/orb/pagerduty/snyk

executors:
  base:
    docker:
      - image: cimg/node:16.13.2
    working_directory: /home/circleci/pdjs

jobs:
  build:
    executor: base
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install NPM
          command: npm ci --prefer-offline
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build packages
          command: npm run build
      - store_artifacts:
          path: dist
  lint:
    executor: base
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install NPM
          command: npm ci --prefer-offline
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Lint
          command: npm run lint
  test:
    executor: base
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install NPM
          command: npm ci --prefer-offline
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Test
          command: npm run test


workflows:
  build-and-test:
    jobs:
      - build
      - lint
      - test
      - snyk/snyk_test_full_scan:
          organization: shared-foundations
          context:
            - PagerDuty
            - Snyk
